<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{11805366-e29e-480f-a6bb-56d282f92711}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU IMPLEMENTS POU.controller
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>